# Transformation Configuration
# Each transformation specifies:
# - source_column: The column to transform
# - function: The transformation function name from transformations.py
# - output_columns: List of output column names (order matters!)
# - description: Optional description of what the transformation does

transformations:
  - source_column: fullname__c
    function: split_firstname_lastname
    output_columns:
      - FirstName
      - LastName
    description: "Split 'FirstName LastName' format into separate columns"

column_order:
  - FirstName
  - LastName
  - id

post_processing:
  drop_duplicates:
    subset:  # Optional: columns to consider for duplicate detection      
      - FirstName
      - LastName
    keep: "first"  # Options: 'first', 'last', or false (remove all duplicates)

  # Add a hash ID column based on row values
  # Simple format: just specify column name (uses MD5 on all columns)
  # add_hash_id: "row_id"

  # Advanced format: specify column name, algorithm, and which columns to hash
  add_hash_id:
    - column_name: "id"
      algorithm: "join"  # Options: md5, sha1, sha256
      subset:  # Optional: only hash these columns (if not specified, uses all columns)
        - FirstName
        - LastName